# Generated by Django 4.2.9 on 2024-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochs', models.IntegerField()),
                ('dataset_type', models.CharField(max_length=100)),
                ('test_size', models.FloatField()),
                ('lr', models.FloatField()),
                ('in_features', models.IntegerField()),
                ('hidden_features', models.IntegerField()),
                ('out_features', models.IntegerField()),
                ('samples', models.IntegerField()),
                ('seed', models.IntegerField()),
                ('noise', models.FloatField()),
                ('classes', models.IntegerField()),
                ('activation', models.CharField(max_length=100)),
                ('layer_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochs', models.IntegerField()),
                ('lr', models.FloatField()),
                ('samples', models.IntegerField()),
                ('test_size', models.FloatField()),
                ('random_state', models.IntegerField()),
                ('noise', models.IntegerField()),
            ],
        ),
    ]
